### ISSUE TITLE
[Backend] Is saving the foodCategory in the backend server really necessary? 

### ISSUE THREAD

**Issue by mushypeas** [swsnu/swpp2020-team5#10]
The behavior I expect from the foodCategory is that it would be reset every time the user signs in - which means, it does not have to save/load any data at the point of signing in/out. Isn't there no point in saving it in the Backend? We could just handle it solely on the frontend side.
Edit: Same issue for searchLocation

**Comment by sugsugsug** [comment]
Ah, that makes sense, because we have sidebar and that can save them as state, we may not need them.

**Comment by sugsugsug** [comment]
Decision: For backend Searching, we need these.
