### ISSUE TITLE
[Method Naming issue] How about adding 'Button' into all button's handler's name?

### ISSUE THREAD

**Issue by sugsugsug** [swsnu/swpp2020-team5#17]
This is somewhat trivial but this can improve consistency

**Comment by magnolia93** [comment]
I think our button handlers already have 'Click' in their name. And we know 'Click' implicitly means button handler.
So I think adding 'Button' into button's handler' name is not needed unless there is something confusing issue.

**Comment by sugsugsug** [comment]
Okay, let's keep original naming convention
