### ISSUE TITLE
MyReview is not showing the content correctly

### ISSUE THREAD

**Issue by magnolia93** [swsnu/swpp2020-team5#40]
On the browser, MyReview's content is not showing at all. 
And During the MyInfoTab testing, I found out that there are three duplicate MyReview for each MyReview. 
Maybe this is related to MyInfoTab but I couldn't find the cause so far. 
So please check this when testing MyReview Component

**Comment by sugsugsug** [comment]
mocking is needed for myreview(it may have same classname).
I fixed
