### ISSUE TITLE
Please add coveralls to your project!

### ISSUE THREAD

**Issue by hy00nc** [swsnu/swpp2020-team5#45]
Please add coveralls to your project to see the coverage metric in the readme until the end of Sprint3.
Refer to https://github.com/swsnu/swppfall2020/blob/master/project/Add%20Badge%20in%20README.pdf on how to add coveralls to your project.
If it works well, you can close this issue. Otherwise, please leave a comment in this issue so that I can take a look.

SonarCloud는 다음 빌드부터 정상적으로 compute 될 겁니다.

**Comment by sugsugsug** [comment]
yarn test ~후에 local에서 돌려봤는데요, 아래와 같은 에러가 납니다.
➜  frontend git:(master) ✗ cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

/home/sug/Desktop/swpp2020-team5/frontend/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
(Use `node --trace-uncaught ...` to show where the exception was thrown)

문제가 무엇일까요?

**Comment by hy00nc** [comment]
local에서는 token이 없어서 아마 안 되는게 맞을 거 같습니다.
Travis CI에서는 자동으로 token을 OAuth를 통해서 가지고 있는 것으로 알고 있어서 repo에 token 설정할 필요 없이 돌 거 같아요.
Travis에서 빌드 돌 때까지 기다리고 로그 한번 보면 좋을 것 같습니다.

**Comment by sugsugsug** [comment]
홈에서 sonar-scanner 가 command not found 에러가 나네요..
 sonar-project.properties 있는 폴더에서 sonar-scanner 치면 되는 것 아닌가요??

**Comment by hy00nc** [comment]
확인해보니 .travis.yml에 sonarcloud addon이 추가 안되어있는 것 같습니다. backend testing에서는 포함되어 있는데 frontend 부분에도 추가해주셔야 할 거 같아요.

추가로, 제가 확인해본 결과 front랑 back을 따로 돌리면 coveralls가 둘 중 하나만 coveralls로 전송되는 걸 확인해서, team4꺼 참고하셔서 .travis.yml 파일 새로 작성하시는 것을 추천드립니다.

**Comment by sugsugsug** [comment]
넵 감사합니다.
