### ISSUE TITLE
[DL]

### ISSUE THREAD

**Issue by sugsugsug** [swsnu/swpp2020-team5#58]
0. 메뉴, 음식점 이름 둘다 검색 되게 -> 종택
1. crawling -> 재문
2. dl -> 우경
  리뷰+위키
  리뷰 content
3. frontend - backend -> 진우
4. update, customized 조정 -> 진우, 종택

5. 배달, user ranking

**Comment by mushypeas** [comment]
- save categories
- save thumbnails
- reasonable tokenization
