### ISSUE TITLE
Integration 이후 확인된 이슈들 정리

### ISSUE THREAD

**Issue by magnolia93** [swsnu/swpp2020-team5#69]
1. Sign up 관련 문제들
   (1) Sign up시 메일 중복여부 체크하는 기능 필요함

2. Sign in 관련 문제들
  (1) Sign in fail했을 때 sign-in 페이지에 머물도록 해야함(현재는 main 페이지에서 not found로 이동함)
  (2) sign in 했을 때 사용자가 위치 정보 허용을 차단시켰을 때 기본 위치 설정해주는 기능이 필요함
  (3) 이미 sign-in 한 유저가 sign-in 페이지로 url로 직접 이동하려고 하면 main으로 redirection 시켜야 함.
 
3. 데이터 형식 불일치 문제
  (1) 프론트 벡터에서 넘겨주는 취향 벡터 데이터 형식 통일되어야 함. (현재 확인된 것은 sign-up2에서 음식 고르는 부분이 프론트에서는 스트링 리스트를 넘겨주고 백엔드에서는 불린 리스트를 이용하고 있어서 오류가 남)

4. 메인 페이지
  (1) 프론트엔드 메인페이지 url 중 'main/' (파라미터 없는 페이지)도 따로 만들어야 함

5. 디테일 페이지
  (1) 프론트엔드 디테일 페이지에서 undefined랑 null 관련 오류 수정 필요

**Comment by sugsugsug** [comment]
2-(2) remaining?
