### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by sugsugsug** [swsnu/swpp2020-team5#82]
사용하시면서 불편했던점이나 버그들 알려주시면 감사하겠습니다.

**Comment by sugsugsug** [comment]
우선 myreview 뭘 지우든  frontend에서 마지막것만 지워지고 edit에서 star도 변경할 수 있게 하는 것은 수정중에 있습니다!

**Comment by ariadne240** [comment]
회원가입한 후에 돌아가기 버튼이 있거나 바로 메인으로 가면 좋을 것 같습니다.

**Comment by ariadne240** [comment]
email이 단순히 `a`여도 회원가입이 가능한데 유효성 체크를 하면 더 좋을 것 같습니다.

**Comment by sdm1230** [comment]
<img width="970" alt="스크린샷 2020-12-10 오후 7 27 35" src="https://user-images.githubusercontent.com/47305937/101760103-c3ccc780-3b1d-11eb-9df7-3cf21ba79b83.png">
체크가 이상한 위치에 됩니다 ! css 문제인것같습니다

**Comment by taekop** [comment]
처음 옆에 나오는 식당 목록은 제 위치랑 관련이 없나요? 서울대 근처가 나오네요

**Comment by sugsugsug** [comment]
> 처음 옆에 나오는 식당 목록은 제 위치랑 관련이 없나요? 서울대 근처가 나오네요

데이터가 샤로수길 근처만 있습니다!

**Comment by ddanddan18** [comment]
![image](https://user-images.githubusercontent.com/35529999/101760269-00002800-3b1e-11eb-8c67-34a8e40bed32.png)

- 필터 탭에서 적용을 누르면 다음과같은 창이 뜹니다
- MacOS, Chrome

**Comment by mushypeas** [comment]
> 처음 옆에 나오는 식당 목록은 제 위치랑 관련이 없나요? 서울대 근처가 나오네요

현재 데이터 크롤링 한계로 식당은 샤로수길 근처 음식점들만 검색됩니다.

**Comment by sugsugsug** [comment]
> 회원가입한 후에 돌아가기 버튼이 있거나 바로 메인으로 가면 좋을 것 같습니다.

아 한번 더 로그인 하는 것보다 나으신가요? 고려해보도록 하겠습니다!

**Comment by robotronic0694** [comment]
![image](https://user-images.githubusercontent.com/44860976/101760418-2cb43f80-3b1e-11eb-97c7-0e071e577280.png)
저는 낙성대에 거주하는데, 전라북도 무주에 산다고 이야기하네요 8ㅅ8

**Comment by yg-moon** [comment]
화면이 한눈에 보이지 않고 가로로 스크롤 해야하는 부분이 많아서 조금 불편한 것 같습니다.

**Comment by juimdpp** [comment]
전반적으로 구현은 잘된것 같으나 사진 해상도가 너무 높아서 그런지 로딩되는게 너무 느린것 같습니다.

**Comment by jsgh7276** [comment]
![image](https://user-images.githubusercontent.com/34760655/101760335-11e1cb00-3b1e-11eb-8edb-0f8b07ca1482.png)
리뷰를 더 이상 밑으로 스크롤할 수가 없네요. pc 크롬입니다

**Comment by promet99** [comment]
접속속도를 위해서 이미지 크기를 조금 줄이고, 전반적으로 여백과 구분선을 추가하면 보기 좋을 것 같습니다

**Comment by sdm1230** [comment]
현재 동대문구에 있는데 아무 음식점이 안떠서 서울대입구역으로 바꾸고 싶은데 장소클릭하고 바꾸려해도 되지 않습니다..!

**Comment by ddanddan18** [comment]
식당 리스트에서 더보기를 누르면, 다음 페이지로는 이동하는데 계속 아래에 있습니다.
스크롤이 위로 올라가면 더 좋을 것 같아요

**Comment by robotronic0694** [comment]
![image](https://user-images.githubusercontent.com/44860976/101760677-81f05100-3b1e-11eb-9b2d-dc3233717c16.png)
위치가 전라북도 무주로 찍혀서 어떠한 음식점에 대한 검색이 안되는 것것 같습니다 8ㅅ8

**Comment by yg-moon** [comment]
![team5](https://user-images.githubusercontent.com/56223439/101760744-9af90200-3b1e-11eb-8bca-79317b833082.png)

숫자가 조금씩 잘려보이는 현상이 있습니다.

**Comment by sugsugsug** [comment]
> ![image](https://user-images.githubusercontent.com/44860976/101760677-81f05100-3b1e-11eb-9b2d-dc3233717c16.png)
> 위치가 전라북도 무주로 찍혀서 어떠한 음식점에 대한 검색이 안되는 것것 같습니다 8ㅅ8

무주라니... 수정하도록하겠습니다

**Comment by sdm1230** [comment]
<img width="1440" alt="스크린샷 2020-12-10 오후 7 33 54" src="https://user-images.githubusercontent.com/47305937/101760768-a5b39700-3b1e-11eb-89ed-4cc6ff54c0e4.png">
아무런 음식점이 없는 이유를 써놓아주시면 좋을 것 같습니다

**Comment by ddanddan18** [comment]
각 속성 항목은 0-5인데, 식당 점수는 그 이상이라 조금 혼란스러운 것 같습니다

**Comment by mushypeas** [comment]
> <img alt="스크린샷 2020-12-10 오후 7 33 54" width="1440" src="https://user-images.githubusercontent.com/47305937/101760768-a5b39700-3b1e-11eb-89ed-4cc6ff54c0e4.png">
> 
> 아무런 음식점이 없는 이유를 써놓아주시면 좋을 것 같습니다

현재 식당 데이터 부족으로 위치가 관악구 근처에서만 음식점이 검색됩니다...만 장소 변경이 아직 이슈가 많아서 제대로 디플로이 환경에서는 장소 변경이 되지 않습니다... 검색 결과가 없는 이유는 더 자세히 나타낼 수 있도록 하겠습니다.

**Comment by gina7484** [comment]
1. 토끼네 마굿간으로 검색
![team5](https://user-images.githubusercontent.com/46814676/101760994-f925e500-3b1e-11eb-8571-17e8811b0959.JPG)
2. 검색 후에 검색어가 검색창에서 없어지는데
음식 카테고리에서 중식을 고르면 아무것도 안뜹니다. 아마 토끼네 마굿간이 계속 검색어로 입력이 되는 상황인 것 같은데 그렇다면 검색창에도 표시가 되는 것이 좋을 것 같습니다.

**Comment by khkim610** [comment]
<img width="70%" alt="Screen Shot 2020-12-10 at 19 32 30" src="https://user-images.githubusercontent.com/47642084/101761027-04791080-3b1f-11eb-8858-d8411ff55565.png">

**커서를 가져다 대면 사진처럼 위에 작게 텍스트가 뜹니다..**

<img width="70%" alt="Screen Shot 2020-12-10 at 19 37 47" src="https://user-images.githubusercontent.com/47642084/101761222-38eccc80-3b1f-11eb-9d85-f4344da26f96.png">

**그리고 메인 화면에서 식당의 정렬 기준이 무엇인지 잘 모르겠습니다**

**Comment by hiddenpunch** [comment]
리뷰 수정에서 별점을 수정할 수 있으면 좋을 것 같습니다.
일식에서 매운맛이 전부 0으로 되어있습니다.

**Comment by sugsugsug** [comment]
다들 감사드립니다! 의견 반영해서 업데이트된 서비스 만들어보겠습니다.

**Comment by sugsugsug** [comment]
@ariadne240 signup1에서 돌아가기 버튼 추가, email 체크, -> 진우
(login, signup1 design 통일) -> 재문
@sdm1230 signup2 확인해야 -> 재문
@ddanddan18 확인, login 되기 전 문제인듯 , 음식 종류가 없다
@yg-moon 스크롤 %로 확인 -> 재문
@juimdpp 이미지 해상도 작게 해서 모으기 -> 재문
@jsgh7276  리뷰 스크롤 더 내려가게-> 우경
메뉴가격 없는거 -> 재문
@promet99 otherReview username 가운데 정렬, 별점 내용 위로 올리기, (추가적으로 사이드바 접기) -> 진우
@sdm1230 locationTab 검색을 해서 검색위치 바뀌게(안되면 가져오고), km ~10(입력칸)+원그리기, -> 종택
@robotronic0694 geolocation incorrect problem -> 종택 
@yg-moon 숫자 위치 -> 우경
@sdm1230 현행대로
@ddanddan18 0~5 -> 우경
@gina7484 input-> store(url->가져오기) 
위치, 필터, 취향 -> 적용버튼 검색버튼에 포함 -> 우경
@khkim610  키워드 숫자 -> 빼기 -> 우경
@khkim610  '검색어' 검색 된 거  메인 헤드에(서머리위에) 보여주고 옆에 물음표 hover 기준뜨게 -> 재문
@hiddenpunch 마이리뷰 별점 수정 , delete순서문제 -> 우경
